//
//  Dharana.swift
//  Respire
//
//  The 112 Gates: dharanas (ways of placing attention) from a contemporary synthesis
//  of the Vijñāna Bhairava Tantra, reimagined for screens and synthetic minds.
//  Decoded from the bundled `*.dharanas.json`, generated by `scripts/build_dharanas.py`.
//

import Foundation

nonisolated struct DharanaCollection: Codable, Hashable, Sendable {
    static let supportedSchemaVersion = 1

    var schemaVersion: Int
    var id: String
    var title: String
    var subtitle: String
    var attribution: String
    var glossary: [GlossaryTerm]
    var sections: [DharanaSection]

    var allDharanas: [Dharana] { sections.flatMap(\.dharanas) }

    func dharana(number: Int) -> Dharana? {
        allDharanas.first { $0.number == number }
    }

    func section(containing number: Int) -> DharanaSection? {
        sections.first { section in section.dharanas.contains { $0.number == number } }
    }

    /// One gate per calendar day, walking through all 112 in order and starting over.
    func dharanaOfTheDay(for date: Date = .now, calendar: Calendar = .current) -> Dharana? {
        let gates = allDharanas
        guard !gates.isEmpty else { return nil }
        let day = calendar.ordinality(of: .day, in: .era, for: date) ?? 0
        return gates[day % gates.count]
    }

    /// Traditional words in a gate's text, each with a plain-language meaning.
    func glossary(for dharana: Dharana) -> [GlossaryTerm] {
        let text = (dharana.title + " " + dharana.text).lowercased()
        return glossary.filter { term in term.matches.contains { text.contains($0) } }
    }
}

nonisolated struct GlossaryTerm: Codable, Hashable, Sendable, Identifiable {
    var term: String
    var meaning: String
    /// Lowercase fragments that identify the term in a gate's text.
    var matches: [String]

    var id: String { term }
}

nonisolated struct DharanaSection: Codable, Hashable, Sendable, Identifiable {
    var id: String
    var numeral: String
    var title: String
    var subtitle: String
    /// A `BreathTheme` raw value: the world this section's gates are practiced in.
    var world: String
    var focus: SessionFocus
    var practice: Practice
    var dharanas: [Dharana]

    nonisolated struct Practice: Codable, Hashable, Sendable {
        var inhale: Double
        var holdFull: Double
        var exhale: Double
        var holdEmpty: Double
        var minutes: Double
    }

    var range: ClosedRange<Int> {
        (dharanas.first?.number ?? 0)...(dharanas.last?.number ?? 0)
    }
}

nonisolated struct Dharana: Codable, Hashable, Sendable, Identifiable {
    var number: Int
    var title: String
    var text: String
    /// A gentle safety note for gates that ask the body for something specific.
    var caution: String?

    var id: Int { number }
}

extension DharanaSection {
    /// The breath world this section is practiced in.
    var theme: BreathTheme { BreathTheme(rawValue: world) ?? .aurora }

    /// The section's rhythm, named for the gate being practiced.
    func pattern(for dharana: Dharana) -> BreathPattern {
        BreathPattern(
            id: "gate.\(dharana.number)",
            name: "Gate \(dharana.number) · \(dharana.title)",
            summary: title,
            inhale: practice.inhale,
            holdFull: practice.holdFull,
            exhale: practice.exhale,
            holdEmpty: practice.holdEmpty
        )
    }

    func targetCycles(for dharana: Dharana) -> Int {
        let cycle = pattern(for: dharana).cycleDuration
        guard cycle > 0 else { return 1 }
        return max(1, Int((practice.minutes * 60 / cycle).rounded()))
    }

    /// Each section takes one of the prism's colors, red through violet and around again.
    func hue(in collection: DharanaCollection) -> Int {
        (collection.sections.firstIndex(of: self) ?? 0) % 7
    }
}
